// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package TIM

import "strconv"

type TimeSystem int8

const (
	/// Greenwich Mean Sidereal Time
	timeSystemGMST TimeSystem = 0
	/// Global Positioning System
	timeSystemGPS  TimeSystem = 1
	/// Mission Elapsed Time
	timeSystemMET  TimeSystem = 2
	/// Mission Relative Time
	timeSystemMRT  TimeSystem = 3
	/// Spacecraft Clock (receiver) (requires rules for interpretation in ICD)
	timeSystemSCLK TimeSystem = 4
	/// International Atomic Time
	timeSystemTAI  TimeSystem = 5
	/// Barycentric Coordinate Time
	timeSystemTCB  TimeSystem = 6
	/// Barycentric Dynamical Time
	timeSystemTDB  TimeSystem = 7
	/// Geocentric Coordinate Time
	timeSystemTCG  TimeSystem = 8
	/// Terrestrial Time
	timeSystemTT   TimeSystem = 9
	/// Universal Time
	timeSystemUT1  TimeSystem = 10
	/// Coordinated Universal Time
	timeSystemUTC  TimeSystem = 11
)

var EnumNamestimeSystem = map[TimeSystem]string{
	timeSystemGMST: "GMST",
	timeSystemGPS:  "GPS",
	timeSystemMET:  "MET",
	timeSystemMRT:  "MRT",
	timeSystemSCLK: "SCLK",
	timeSystemTAI:  "TAI",
	timeSystemTCB:  "TCB",
	timeSystemTDB:  "TDB",
	timeSystemTCG:  "TCG",
	timeSystemTT:   "TT",
	timeSystemUT1:  "UT1",
	timeSystemUTC:  "UTC",
}

var EnumValuestimeSystem = map[string]TimeSystem{
	"GMST": timeSystemGMST,
	"GPS":  timeSystemGPS,
	"MET":  timeSystemMET,
	"MRT":  timeSystemMRT,
	"SCLK": timeSystemSCLK,
	"TAI":  timeSystemTAI,
	"TCB":  timeSystemTCB,
	"TDB":  timeSystemTDB,
	"TCG":  timeSystemTCG,
	"TT":   timeSystemTT,
	"UT1":  timeSystemUT1,
	"UTC":  timeSystemUTC,
}

func (v TimeSystem) String() string {
	if s, ok := EnumNamestimeSystem[v]; ok {
		return s
	}
	return "timeSystem(" + strconv.FormatInt(int64(v), 10) + ")"
}
