// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package LCC

import "strconv"

type LegacyCountryCode int8

const (
	/// Arab Satellite Communications Organization
	legacyCountryCodeAB   LegacyCountryCode = 0
	/// Asia Broadcast Satellite
	legacyCountryCodeABS  LegacyCountryCode = 1
	/// Asia Satellite Telecommunications Company (ASIASAT)
	legacyCountryCodeAC   LegacyCountryCode = 2
	/// Algeria
	legacyCountryCodeALG  LegacyCountryCode = 3
	/// Angola
	legacyCountryCodeANG  LegacyCountryCode = 4
	/// Argentina
	legacyCountryCodeARGN LegacyCountryCode = 5
	/// Republic of Armenia
	legacyCountryCodeARM  LegacyCountryCode = 6
	/// Austria
	legacyCountryCodeASRA LegacyCountryCode = 7
	/// Australia
	legacyCountryCodeAUS  LegacyCountryCode = 8
	/// Azerbaijan
	legacyCountryCodeAZER LegacyCountryCode = 9
	/// Belgium
	legacyCountryCodeBEL  LegacyCountryCode = 10
	/// Belarus
	legacyCountryCodeBELA LegacyCountryCode = 11
	/// Bermuda
	legacyCountryCodeBERM LegacyCountryCode = 12
	/// People's Republic of Bangladesh
	legacyCountryCodeBGD  LegacyCountryCode = 13
	/// Kingdom of Bhutan
	legacyCountryCodeBHUT LegacyCountryCode = 14
	/// Bolivia
	legacyCountryCodeBOL  LegacyCountryCode = 15
	/// Brazil
	legacyCountryCodeBRAZ LegacyCountryCode = 16
	/// Bulgaria
	legacyCountryCodeBUL  LegacyCountryCode = 17
	/// Canada
	legacyCountryCodeCA   LegacyCountryCode = 18
	/// China/Brazil
	legacyCountryCodeCHBZ LegacyCountryCode = 19
	/// China/Turkey
	legacyCountryCodeCHTU LegacyCountryCode = 20
	/// Chile
	legacyCountryCodeCHLE LegacyCountryCode = 21
	/// Commonwealth of Independent States (former USSR)
	legacyCountryCodeCIS  LegacyCountryCode = 22
	/// Colombia
	legacyCountryCodeCOL  LegacyCountryCode = 23
	/// Republic of Costa Rica
	legacyCountryCodeCRI  LegacyCountryCode = 24
	/// Czech Republic (former Czechoslovakia)
	legacyCountryCodeCZCH LegacyCountryCode = 25
	/// Denmark
	legacyCountryCodeDEN  LegacyCountryCode = 26
	/// Republic of Djibouti
	legacyCountryCodeDJI  LegacyCountryCode = 27
	/// Ecuador
	legacyCountryCodeECU  LegacyCountryCode = 28
	/// Egypt
	legacyCountryCodeEGYP LegacyCountryCode = 29
	/// European Space Agency
	legacyCountryCodeESA  LegacyCountryCode = 30
	/// European Space Research Organization
	legacyCountryCodeESRO LegacyCountryCode = 31
	/// Estonia
	legacyCountryCodeEST  LegacyCountryCode = 32
	/// Ethiopia
	legacyCountryCodeETH  LegacyCountryCode = 33
	/// European Organization for the Exploitation of Meteorological Satellites (EUMETSAT)
	legacyCountryCodeEUME LegacyCountryCode = 34
	/// European Telecommunications Satellite Organization (EUTELSAT)
	legacyCountryCodeEUTE LegacyCountryCode = 35
	/// France/Germany
	legacyCountryCodeFGER LegacyCountryCode = 36
	/// Finland
	legacyCountryCodeFIN  LegacyCountryCode = 37
	/// France
	legacyCountryCodeFR   LegacyCountryCode = 38
	/// France/Italy
	legacyCountryCodeFRIT LegacyCountryCode = 39
	/// Germany
	legacyCountryCodeGER  LegacyCountryCode = 40
	/// Republic of Ghana
	legacyCountryCodeGHA  LegacyCountryCode = 41
	/// Globalstar
	legacyCountryCodeGLOB LegacyCountryCode = 42
	/// Greece
	legacyCountryCodeGREC LegacyCountryCode = 43
	/// Greece/Saudi Arabia
	legacyCountryCodeGRSA LegacyCountryCode = 44
	/// Guatemala
	legacyCountryCodeGUAT LegacyCountryCode = 45
	/// Hungary
	legacyCountryCodeHUN  LegacyCountryCode = 46
	/// International Mobile Satellite Organization (INMARSAT)
	legacyCountryCodeIM   LegacyCountryCode = 47
	/// India
	legacyCountryCodeIND  LegacyCountryCode = 48
	/// Indonesia
	legacyCountryCodeINDO LegacyCountryCode = 49
	/// Iran
	legacyCountryCodeIRAN LegacyCountryCode = 50
	/// Iraq
	legacyCountryCodeIRAQ LegacyCountryCode = 51
	/// Iridium
	legacyCountryCodeIRID LegacyCountryCode = 52
	/// Ireland
	legacyCountryCodeIRL  LegacyCountryCode = 53
	/// Israel
	legacyCountryCodeISRA LegacyCountryCode = 54
	/// Indian Space Research Organisation
	legacyCountryCodeISRO LegacyCountryCode = 55
	/// International Space Station
	legacyCountryCodeISS  LegacyCountryCode = 56
	/// Italy
	legacyCountryCodeIT   LegacyCountryCode = 57
	/// International Telecommunications Satellite Organization (INTELSAT)
	legacyCountryCodeITSO LegacyCountryCode = 58
	/// Japan
	legacyCountryCodeJPN  LegacyCountryCode = 59
	/// Kazakhstan
	legacyCountryCodeKAZ  LegacyCountryCode = 60
	/// Republic of Kenya
	legacyCountryCodeKEN  LegacyCountryCode = 61
	/// Laos
	legacyCountryCodeLAOS LegacyCountryCode = 62
	/// Democratic Socialist Republic of Sri Lanka
	legacyCountryCodeLKA  LegacyCountryCode = 63
	/// Lithuania
	legacyCountryCodeLTU  LegacyCountryCode = 64
	/// Luxembourg
	legacyCountryCodeLUXE LegacyCountryCode = 65
	/// Morocco
	legacyCountryCodeMA   LegacyCountryCode = 66
	/// Malaysia
	legacyCountryCodeMALA LegacyCountryCode = 67
	/// Principality of Monaco
	legacyCountryCodeMCO  LegacyCountryCode = 68
	/// Republic of Moldova
	legacyCountryCodeMDA  LegacyCountryCode = 69
	/// Mexico
	legacyCountryCodeMEX  LegacyCountryCode = 70
	/// Republic of the Union of Myanmar
	legacyCountryCodeMMR  LegacyCountryCode = 71
	/// Mongolia
	legacyCountryCodeMNG  LegacyCountryCode = 72
	/// Mauritius
	legacyCountryCodeMUS  LegacyCountryCode = 73
	/// North Atlantic Treaty Organization
	legacyCountryCodeNATO LegacyCountryCode = 74
	/// Netherlands
	legacyCountryCodeNETH LegacyCountryCode = 75
	/// New ICO
	legacyCountryCodeNICO LegacyCountryCode = 76
	/// Nigeria
	legacyCountryCodeNIG  LegacyCountryCode = 77
	/// Democratic People's Republic of Korea
	legacyCountryCodeNKOR LegacyCountryCode = 78
	/// Norway
	legacyCountryCodeNOR  LegacyCountryCode = 79
	/// Federal Democratic Republic of Nepal
	legacyCountryCodeNPL  LegacyCountryCode = 80
	/// New Zealand
	legacyCountryCodeNZ   LegacyCountryCode = 81
	/// O3b Networks
	legacyCountryCodeO3B  LegacyCountryCode = 82
	/// ORBCOMM
	legacyCountryCodeORB  LegacyCountryCode = 83
	/// Pakistan
	legacyCountryCodePAKI LegacyCountryCode = 84
	/// Peru
	legacyCountryCodePERU LegacyCountryCode = 85
	/// Poland
	legacyCountryCodePOL  LegacyCountryCode = 86
	/// Portugal
	legacyCountryCodePOR  LegacyCountryCode = 87
	/// People's Republic of China
	legacyCountryCodePRC  LegacyCountryCode = 88
	/// Republic of Paraguay
	legacyCountryCodePRY  LegacyCountryCode = 89
	/// People's Republic of China/European Space Agency
	legacyCountryCodePRES LegacyCountryCode = 90
	/// State of Qatar
	legacyCountryCodeQAT  LegacyCountryCode = 91
	/// RascomStar-QAF
	legacyCountryCodeRASC LegacyCountryCode = 92
	/// Taiwan (Republic of China)
	legacyCountryCodeROC  LegacyCountryCode = 93
	/// Romania
	legacyCountryCodeROM  LegacyCountryCode = 94
	/// Philippines (Republic of the Philippines)
	legacyCountryCodeRP   LegacyCountryCode = 95
	/// Republic of Rwanda
	legacyCountryCodeRWA  LegacyCountryCode = 96
	/// South Africa
	legacyCountryCodeSAFR LegacyCountryCode = 97
	/// Saudi Arabia
	legacyCountryCodeSAUD LegacyCountryCode = 98
	/// Republic of Sudan
	legacyCountryCodeSDN  LegacyCountryCode = 99
	/// Sea Launch
	legacyCountryCodeSEAL LegacyCountryCode = 100
	/// SES
	legacyCountryCodeSES  LegacyCountryCode = 101
	/// Singapore/Japan
	legacyCountryCodeSGJP LegacyCountryCode = 102
	/// Singapore
	legacyCountryCodeSING LegacyCountryCode = 103
	/// Republic of Korea
	legacyCountryCodeSKOR LegacyCountryCode = 104
	/// Spain
	legacyCountryCodeSPN  LegacyCountryCode = 105
	/// Singapore/Taiwan
	legacyCountryCodeSTCT LegacyCountryCode = 106
	/// Slovenia
	legacyCountryCodeSVN  LegacyCountryCode = 107
	/// Sweden
	legacyCountryCodeSWED LegacyCountryCode = 108
	/// Switzerland
	legacyCountryCodeSWTZ LegacyCountryCode = 109
	/// To Be Determined
	legacyCountryCodeTBD  LegacyCountryCode = 110
	/// Thailand
	legacyCountryCodeTHAI LegacyCountryCode = 111
	/// Turkmenistan/Monaco
	legacyCountryCodeTMMC LegacyCountryCode = 112
	/// Republic of Tunisia
	legacyCountryCodeTUN  LegacyCountryCode = 113
	/// Turkey
	legacyCountryCodeTURK LegacyCountryCode = 114
	/// United Arab Emirates
	legacyCountryCodeUAE  LegacyCountryCode = 115
	/// United Kingdom
	legacyCountryCodeUK   LegacyCountryCode = 116
	/// Ukraine
	legacyCountryCodeUKR  LegacyCountryCode = 117
	/// Unknown
	legacyCountryCodeUNK  LegacyCountryCode = 118
	/// Uruguay
	legacyCountryCodeURY  LegacyCountryCode = 119
	/// United States
	legacyCountryCodeUS   LegacyCountryCode = 120
	/// United States/Brazil
	legacyCountryCodeUSBZ LegacyCountryCode = 121
	/// Vatican City State
	legacyCountryCodeVAT  LegacyCountryCode = 122
	/// Venezuela
	legacyCountryCodeVENZ LegacyCountryCode = 123
	/// Vietnam
	legacyCountryCodeVTNM LegacyCountryCode = 124
	/// Republic of Zimbabwe
	legacyCountryCodeZWE  LegacyCountryCode = 125
)

var EnumNameslegacyCountryCode = map[LegacyCountryCode]string{
	legacyCountryCodeAB:   "AB",
	legacyCountryCodeABS:  "ABS",
	legacyCountryCodeAC:   "AC",
	legacyCountryCodeALG:  "ALG",
	legacyCountryCodeANG:  "ANG",
	legacyCountryCodeARGN: "ARGN",
	legacyCountryCodeARM:  "ARM",
	legacyCountryCodeASRA: "ASRA",
	legacyCountryCodeAUS:  "AUS",
	legacyCountryCodeAZER: "AZER",
	legacyCountryCodeBEL:  "BEL",
	legacyCountryCodeBELA: "BELA",
	legacyCountryCodeBERM: "BERM",
	legacyCountryCodeBGD:  "BGD",
	legacyCountryCodeBHUT: "BHUT",
	legacyCountryCodeBOL:  "BOL",
	legacyCountryCodeBRAZ: "BRAZ",
	legacyCountryCodeBUL:  "BUL",
	legacyCountryCodeCA:   "CA",
	legacyCountryCodeCHBZ: "CHBZ",
	legacyCountryCodeCHTU: "CHTU",
	legacyCountryCodeCHLE: "CHLE",
	legacyCountryCodeCIS:  "CIS",
	legacyCountryCodeCOL:  "COL",
	legacyCountryCodeCRI:  "CRI",
	legacyCountryCodeCZCH: "CZCH",
	legacyCountryCodeDEN:  "DEN",
	legacyCountryCodeDJI:  "DJI",
	legacyCountryCodeECU:  "ECU",
	legacyCountryCodeEGYP: "EGYP",
	legacyCountryCodeESA:  "ESA",
	legacyCountryCodeESRO: "ESRO",
	legacyCountryCodeEST:  "EST",
	legacyCountryCodeETH:  "ETH",
	legacyCountryCodeEUME: "EUME",
	legacyCountryCodeEUTE: "EUTE",
	legacyCountryCodeFGER: "FGER",
	legacyCountryCodeFIN:  "FIN",
	legacyCountryCodeFR:   "FR",
	legacyCountryCodeFRIT: "FRIT",
	legacyCountryCodeGER:  "GER",
	legacyCountryCodeGHA:  "GHA",
	legacyCountryCodeGLOB: "GLOB",
	legacyCountryCodeGREC: "GREC",
	legacyCountryCodeGRSA: "GRSA",
	legacyCountryCodeGUAT: "GUAT",
	legacyCountryCodeHUN:  "HUN",
	legacyCountryCodeIM:   "IM",
	legacyCountryCodeIND:  "IND",
	legacyCountryCodeINDO: "INDO",
	legacyCountryCodeIRAN: "IRAN",
	legacyCountryCodeIRAQ: "IRAQ",
	legacyCountryCodeIRID: "IRID",
	legacyCountryCodeIRL:  "IRL",
	legacyCountryCodeISRA: "ISRA",
	legacyCountryCodeISRO: "ISRO",
	legacyCountryCodeISS:  "ISS",
	legacyCountryCodeIT:   "IT",
	legacyCountryCodeITSO: "ITSO",
	legacyCountryCodeJPN:  "JPN",
	legacyCountryCodeKAZ:  "KAZ",
	legacyCountryCodeKEN:  "KEN",
	legacyCountryCodeLAOS: "LAOS",
	legacyCountryCodeLKA:  "LKA",
	legacyCountryCodeLTU:  "LTU",
	legacyCountryCodeLUXE: "LUXE",
	legacyCountryCodeMA:   "MA",
	legacyCountryCodeMALA: "MALA",
	legacyCountryCodeMCO:  "MCO",
	legacyCountryCodeMDA:  "MDA",
	legacyCountryCodeMEX:  "MEX",
	legacyCountryCodeMMR:  "MMR",
	legacyCountryCodeMNG:  "MNG",
	legacyCountryCodeMUS:  "MUS",
	legacyCountryCodeNATO: "NATO",
	legacyCountryCodeNETH: "NETH",
	legacyCountryCodeNICO: "NICO",
	legacyCountryCodeNIG:  "NIG",
	legacyCountryCodeNKOR: "NKOR",
	legacyCountryCodeNOR:  "NOR",
	legacyCountryCodeNPL:  "NPL",
	legacyCountryCodeNZ:   "NZ",
	legacyCountryCodeO3B:  "O3B",
	legacyCountryCodeORB:  "ORB",
	legacyCountryCodePAKI: "PAKI",
	legacyCountryCodePERU: "PERU",
	legacyCountryCodePOL:  "POL",
	legacyCountryCodePOR:  "POR",
	legacyCountryCodePRC:  "PRC",
	legacyCountryCodePRY:  "PRY",
	legacyCountryCodePRES: "PRES",
	legacyCountryCodeQAT:  "QAT",
	legacyCountryCodeRASC: "RASC",
	legacyCountryCodeROC:  "ROC",
	legacyCountryCodeROM:  "ROM",
	legacyCountryCodeRP:   "RP",
	legacyCountryCodeRWA:  "RWA",
	legacyCountryCodeSAFR: "SAFR",
	legacyCountryCodeSAUD: "SAUD",
	legacyCountryCodeSDN:  "SDN",
	legacyCountryCodeSEAL: "SEAL",
	legacyCountryCodeSES:  "SES",
	legacyCountryCodeSGJP: "SGJP",
	legacyCountryCodeSING: "SING",
	legacyCountryCodeSKOR: "SKOR",
	legacyCountryCodeSPN:  "SPN",
	legacyCountryCodeSTCT: "STCT",
	legacyCountryCodeSVN:  "SVN",
	legacyCountryCodeSWED: "SWED",
	legacyCountryCodeSWTZ: "SWTZ",
	legacyCountryCodeTBD:  "TBD",
	legacyCountryCodeTHAI: "THAI",
	legacyCountryCodeTMMC: "TMMC",
	legacyCountryCodeTUN:  "TUN",
	legacyCountryCodeTURK: "TURK",
	legacyCountryCodeUAE:  "UAE",
	legacyCountryCodeUK:   "UK",
	legacyCountryCodeUKR:  "UKR",
	legacyCountryCodeUNK:  "UNK",
	legacyCountryCodeURY:  "URY",
	legacyCountryCodeUS:   "US",
	legacyCountryCodeUSBZ: "USBZ",
	legacyCountryCodeVAT:  "VAT",
	legacyCountryCodeVENZ: "VENZ",
	legacyCountryCodeVTNM: "VTNM",
	legacyCountryCodeZWE:  "ZWE",
}

var EnumValueslegacyCountryCode = map[string]LegacyCountryCode{
	"AB":   legacyCountryCodeAB,
	"ABS":  legacyCountryCodeABS,
	"AC":   legacyCountryCodeAC,
	"ALG":  legacyCountryCodeALG,
	"ANG":  legacyCountryCodeANG,
	"ARGN": legacyCountryCodeARGN,
	"ARM":  legacyCountryCodeARM,
	"ASRA": legacyCountryCodeASRA,
	"AUS":  legacyCountryCodeAUS,
	"AZER": legacyCountryCodeAZER,
	"BEL":  legacyCountryCodeBEL,
	"BELA": legacyCountryCodeBELA,
	"BERM": legacyCountryCodeBERM,
	"BGD":  legacyCountryCodeBGD,
	"BHUT": legacyCountryCodeBHUT,
	"BOL":  legacyCountryCodeBOL,
	"BRAZ": legacyCountryCodeBRAZ,
	"BUL":  legacyCountryCodeBUL,
	"CA":   legacyCountryCodeCA,
	"CHBZ": legacyCountryCodeCHBZ,
	"CHTU": legacyCountryCodeCHTU,
	"CHLE": legacyCountryCodeCHLE,
	"CIS":  legacyCountryCodeCIS,
	"COL":  legacyCountryCodeCOL,
	"CRI":  legacyCountryCodeCRI,
	"CZCH": legacyCountryCodeCZCH,
	"DEN":  legacyCountryCodeDEN,
	"DJI":  legacyCountryCodeDJI,
	"ECU":  legacyCountryCodeECU,
	"EGYP": legacyCountryCodeEGYP,
	"ESA":  legacyCountryCodeESA,
	"ESRO": legacyCountryCodeESRO,
	"EST":  legacyCountryCodeEST,
	"ETH":  legacyCountryCodeETH,
	"EUME": legacyCountryCodeEUME,
	"EUTE": legacyCountryCodeEUTE,
	"FGER": legacyCountryCodeFGER,
	"FIN":  legacyCountryCodeFIN,
	"FR":   legacyCountryCodeFR,
	"FRIT": legacyCountryCodeFRIT,
	"GER":  legacyCountryCodeGER,
	"GHA":  legacyCountryCodeGHA,
	"GLOB": legacyCountryCodeGLOB,
	"GREC": legacyCountryCodeGREC,
	"GRSA": legacyCountryCodeGRSA,
	"GUAT": legacyCountryCodeGUAT,
	"HUN":  legacyCountryCodeHUN,
	"IM":   legacyCountryCodeIM,
	"IND":  legacyCountryCodeIND,
	"INDO": legacyCountryCodeINDO,
	"IRAN": legacyCountryCodeIRAN,
	"IRAQ": legacyCountryCodeIRAQ,
	"IRID": legacyCountryCodeIRID,
	"IRL":  legacyCountryCodeIRL,
	"ISRA": legacyCountryCodeISRA,
	"ISRO": legacyCountryCodeISRO,
	"ISS":  legacyCountryCodeISS,
	"IT":   legacyCountryCodeIT,
	"ITSO": legacyCountryCodeITSO,
	"JPN":  legacyCountryCodeJPN,
	"KAZ":  legacyCountryCodeKAZ,
	"KEN":  legacyCountryCodeKEN,
	"LAOS": legacyCountryCodeLAOS,
	"LKA":  legacyCountryCodeLKA,
	"LTU":  legacyCountryCodeLTU,
	"LUXE": legacyCountryCodeLUXE,
	"MA":   legacyCountryCodeMA,
	"MALA": legacyCountryCodeMALA,
	"MCO":  legacyCountryCodeMCO,
	"MDA":  legacyCountryCodeMDA,
	"MEX":  legacyCountryCodeMEX,
	"MMR":  legacyCountryCodeMMR,
	"MNG":  legacyCountryCodeMNG,
	"MUS":  legacyCountryCodeMUS,
	"NATO": legacyCountryCodeNATO,
	"NETH": legacyCountryCodeNETH,
	"NICO": legacyCountryCodeNICO,
	"NIG":  legacyCountryCodeNIG,
	"NKOR": legacyCountryCodeNKOR,
	"NOR":  legacyCountryCodeNOR,
	"NPL":  legacyCountryCodeNPL,
	"NZ":   legacyCountryCodeNZ,
	"O3B":  legacyCountryCodeO3B,
	"ORB":  legacyCountryCodeORB,
	"PAKI": legacyCountryCodePAKI,
	"PERU": legacyCountryCodePERU,
	"POL":  legacyCountryCodePOL,
	"POR":  legacyCountryCodePOR,
	"PRC":  legacyCountryCodePRC,
	"PRY":  legacyCountryCodePRY,
	"PRES": legacyCountryCodePRES,
	"QAT":  legacyCountryCodeQAT,
	"RASC": legacyCountryCodeRASC,
	"ROC":  legacyCountryCodeROC,
	"ROM":  legacyCountryCodeROM,
	"RP":   legacyCountryCodeRP,
	"RWA":  legacyCountryCodeRWA,
	"SAFR": legacyCountryCodeSAFR,
	"SAUD": legacyCountryCodeSAUD,
	"SDN":  legacyCountryCodeSDN,
	"SEAL": legacyCountryCodeSEAL,
	"SES":  legacyCountryCodeSES,
	"SGJP": legacyCountryCodeSGJP,
	"SING": legacyCountryCodeSING,
	"SKOR": legacyCountryCodeSKOR,
	"SPN":  legacyCountryCodeSPN,
	"STCT": legacyCountryCodeSTCT,
	"SVN":  legacyCountryCodeSVN,
	"SWED": legacyCountryCodeSWED,
	"SWTZ": legacyCountryCodeSWTZ,
	"TBD":  legacyCountryCodeTBD,
	"THAI": legacyCountryCodeTHAI,
	"TMMC": legacyCountryCodeTMMC,
	"TUN":  legacyCountryCodeTUN,
	"TURK": legacyCountryCodeTURK,
	"UAE":  legacyCountryCodeUAE,
	"UK":   legacyCountryCodeUK,
	"UKR":  legacyCountryCodeUKR,
	"UNK":  legacyCountryCodeUNK,
	"URY":  legacyCountryCodeURY,
	"US":   legacyCountryCodeUS,
	"USBZ": legacyCountryCodeUSBZ,
	"VAT":  legacyCountryCodeVAT,
	"VENZ": legacyCountryCodeVENZ,
	"VTNM": legacyCountryCodeVTNM,
	"ZWE":  legacyCountryCodeZWE,
}

func (v LegacyCountryCode) String() string {
	if s, ok := EnumNameslegacyCountryCode[v]; ok {
		return s
	}
	return "legacyCountryCode(" + strconv.FormatInt(int64(v), 10) + ")"
}
