// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package IDM

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Frequency range with lower and upper limits
type FrequencyRange struct {
	_tab flatbuffers.Table
}

func GetRootAsFrequencyRange(buf []byte, offset flatbuffers.UOffsetT) *FrequencyRange {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FrequencyRange{}
	x.Init(buf, n+offset)
	return x
}

func FinishFrequencyRangeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFrequencyRange(buf []byte, offset flatbuffers.UOffsetT) *FrequencyRange {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FrequencyRange{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFrequencyRangeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FrequencyRange) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FrequencyRange) Table() flatbuffers.Table {
	return rcv._tab
}

/// Lower frequency in MHz
func (rcv *FrequencyRange) Lower() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

/// Lower frequency in MHz
func (rcv *FrequencyRange) MutateLower(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

/// Upper frequency in MHz
func (rcv *FrequencyRange) Upper() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

/// Upper frequency in MHz
func (rcv *FrequencyRange) MutateUpper(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func FrequencyRangeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FrequencyRangeAddLower(builder *flatbuffers.Builder, lower float64) {
	builder.PrependFloat64Slot(0, lower, 0.0)
}
func FrequencyRangeAddUpper(builder *flatbuffers.Builder, upper float64) {
	builder.PrependFloat64Slot(1, upper, 0.0)
}
func FrequencyRangeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
